"""empty message

Revision ID: de286b479760
Revises: 61f657471a20
Create Date: 2020-07-25 17:50:24.567077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de286b479760'
down_revision = '61f657471a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.drop_column('user', 'fist_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fist_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
